import type { Task } from "./types";

/**
 * Seeded task catalogue.
 *
 * These are demonstration tasks written for the build: the names, slot counts,
 * pass rates and medians are synthetic and labelled as such wherever they are
 * shown. Real tasks are read from the TaskRegistry on Monad; nothing here is
 * presented as live network data.
 */
export const TASKS: Task[] = [
  {
    id: "AX-0114",
    name: "Put the toothpaste into the upper drawer",
    object: "toothpaste",
    scenario: "bathroom",
    skills: ["pick", "insert"],
    difficulty: 3,
    stage: "pre",
    slotsFilled: 779,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.42,
    passRate: 0.8154,
    medianSeconds: 125,
    steps: [
      "Pull the upper drawer fully out",
      "Pick up the toothpaste",
      "Place the toothpaste into the drawer",
    ],
  },
  {
    id: "AX-0115",
    name: "Put the screwdriver into the upper drawer",
    object: "screwdriver",
    scenario: "workshop",
    skills: ["pick", "insert"],
    difficulty: 3,
    stage: "pre",
    slotsFilled: 972,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.4,
    passRate: 0.7902,
    medianSeconds: 131,
    steps: [
      "Pull the upper drawer fully out",
      "Pick up the screwdriver",
      "Place the screwdriver into the drawer",
    ],
  },
  {
    id: "AX-0121",
    name: "Put the apricot into the air fryer",
    object: "apricot",
    scenario: "kitchen",
    skills: ["pick", "place"],
    difficulty: 2,
    stage: "pre",
    slotsFilled: 397,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.36,
    passRate: 0.8613,
    medianSeconds: 98,
    steps: ["Open the air fryer", "Pick up the apricot", "Place the apricot inside"],
  },
  {
    id: "AX-0127",
    name: "Put the banana into the microwave",
    object: "banana",
    scenario: "kitchen",
    skills: ["pick", "place"],
    difficulty: 2,
    stage: "pre",
    slotsFilled: 867,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.34,
    passRate: 0.8871,
    medianSeconds: 91,
    steps: ["Open the microwave door", "Pick up the banana", "Place the banana inside"],
  },
  {
    id: "AX-0133",
    name: "Put the pen on the closed laptop",
    object: "pen",
    scenario: "office",
    skills: ["pick", "place"],
    difficulty: 2,
    stage: "pre",
    slotsFilled: 821,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.32,
    passRate: 0.9012,
    medianSeconds: 74,
    steps: ["Pick up the pen", "Place the pen on the laptop lid"],
  },
  {
    id: "AX-0140",
    name: "Put the shrimp to the left of the honey jar",
    object: "shrimp",
    scenario: "kitchen",
    skills: ["pick", "arrange"],
    difficulty: 4,
    stage: "pre",
    slotsFilled: 47,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.68,
    passRate: 0.6104,
    medianSeconds: 168,
    steps: [
      "Pick up the shrimp",
      "Move it left of the honey jar",
      "Release without disturbing the jar",
    ],
  },
  {
    id: "AX-0142",
    name: "Stack the small honey jar behind the toast",
    object: "honey jar",
    scenario: "kitchen",
    skills: ["pick", "stack", "arrange"],
    difficulty: 4,
    stage: "pre",
    slotsFilled: 293,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.64,
    passRate: 0.6547,
    medianSeconds: 154,
    steps: ["Pick up the honey jar", "Position it behind the toast", "Release"],
  },
  {
    id: "AX-0148",
    name: "Rotate the dice to show four",
    object: "dice",
    scenario: "play",
    skills: ["pick", "rotate"],
    difficulty: 5,
    stage: "pre",
    slotsFilled: 112,
    slotsTotal: 900,
    rewardPerTrajectory: 0.94,
    passRate: 0.4821,
    medianSeconds: 201,
    steps: ["Pick up the dice", "Rotate until four faces up", "Set it back down"],
  },
  {
    id: "AX-0151",
    name: "Insert the eraser into the pen cup",
    object: "eraser",
    scenario: "office",
    skills: ["pick", "insert"],
    difficulty: 3,
    stage: "pre",
    slotsFilled: 1025,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.38,
    passRate: 0.8331,
    medianSeconds: 112,
    steps: ["Pick up the eraser", "Align above the cup", "Insert"],
  },
  {
    id: "AX-0104",
    name: "Transfer the hot dog to the right of the cucumber",
    object: "hot dog",
    scenario: "kitchen",
    skills: ["pick", "transfer"],
    difficulty: 3,
    stage: "training",
    slotsFilled: 1200,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.44,
    passRate: 0.7715,
    medianSeconds: 138,
    steps: ["Pick up the hot dog", "Transfer right of the cucumber", "Release"],
  },
  {
    id: "AX-0096",
    name: "Separate the spoon from the toast",
    object: "spoon",
    scenario: "kitchen",
    skills: ["pick", "separate"],
    difficulty: 3,
    stage: "training",
    slotsFilled: 1200,
    slotsTotal: 1200,
    rewardPerTrajectory: 0.41,
    passRate: 0.8004,
    medianSeconds: 121,
    steps: ["Grip the spoon handle", "Lift clear of the toast", "Set down apart"],
  },
  {
    id: "AX-0071",
    name: "Reach the far shelf and place the mug",
    object: "mug",
    scenario: "home",
    skills: ["reach", "place"],
    difficulty: 5,
    stage: "post",
    slotsFilled: 640,
    slotsTotal: 800,
    rewardPerTrajectory: 1.1,
    passRate: 0.5533,
    medianSeconds: 187,
    steps: ["Pick up the mug", "Extend to the far shelf", "Place without tipping"],
  },
];

export const getTask = (id: string) => TASKS.find((t) => t.id === id);

export const OPEN_TASKS = TASKS.filter((t) => t.stage === "pre");
