/**
 * Emit the read interfaces the app needs, straight from the Foundry artifacts.
 *
 * Hand-copying an ABI is how a frontend ends up calling a function the deployed
 * contract does not have. Every entry below is sliced out of contracts/out at
 * generation time, so it cannot describe anything the compiler did not produce.
 *
 *   node scripts/gen-abi.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const WANT = {
  TrajectoryCertificate: ["minted", "ownerOf", "tokenURI", "balanceOf", "name", "symbol"],
  ContributionRecord: ["balanceOf", "pending", "totalSupply", "decimals", "symbol", "name"],
  Referrals: ["bounty", "remaining", "paidOut", "referrerOf", "referredBy", "MAX_PER_REFERRER", "MIN_NEWCOMER_WEIGHT"],
  PrizePool: ["taskId", "closesAt", "entrantCount", "totalWeight", "settled", "weightOf", "projected", "entrants"],
  Foundry: ["proposalCount", "getProposal", "VOTING_PERIOD", "MIN_WEIGHT_TO_PROPOSE", "cost"],
  ConfidentialPayouts: ["totalOf", "keyOf", "entries"],
  LicenceReceipt: ["payloadFor", "sourceChain", "FORMAT"],
};

let out = `// Generated by scripts/gen-abi.mjs from contracts/out — do not edit by hand.\n`;
out += `// Only the reads the interface actually makes; regenerate after a contract change.\n\n`;

for (const [name, fns] of Object.entries(WANT)) {
  const artifact = JSON.parse(readFileSync(`contracts/out/${name}.sol/${name}.json`, "utf8"));
  const picked = artifact.abi.filter((e) => e.type === "function" && fns.includes(e.name));
  const missing = fns.filter((f) => !picked.some((p) => p.name === f));
  if (missing.length) throw new Error(`${name}: artifact has no ${missing.join(", ")}`);
  const konst = name.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase() + "_ABI";
  out += `export const ${konst} = ${JSON.stringify(picked, null, 2)} as const;\n\n`;
}
writeFileSync("lib/registry-abi.ts", out);
console.log(`lib/registry-abi.ts — ${Object.keys(WANT).length} contracts, ${out.split("\n").length} lines`);
