/**
 * Emit the read interfaces the app needs, straight from the Foundry artifacts.
 *
 * Hand-copying an ABI is how a frontend ends up calling a function the deployed
 * contract does not have. Every entry below is sliced out of contracts/out at
 * generation time, so it cannot describe anything the compiler did not produce.
 *
 *   node scripts/gen-abi.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const WANT = {
  TrajectoryCertificate: ["minted", "ownerOf", "tokenURI", "balanceOf", "name", "symbol"],
  ContributionRecord: ["balanceOf", "pending", "totalSupply", "decimals", "symbol", "name"],
  Referrals: ["bounty", "remaining", "paidOut", "referrerOf", "referredBy", "MAX_PER_REFERRER", "MIN_NEWCOMER_WEIGHT"],
  PrizePool: ["taskId", "closesAt", "entrantCount", "totalWeight", "settled", "weightOf", "projected", "entrants"],
  Foundry: ["proposalCount", "getProposal", "VOTING_PERIOD", "MIN_WEIGHT_TO_PROPOSE", "cost"],
  ConfidentialPayouts: ["totalOf", "keyOf", "entries"],
  LicenceReceipt: ["payloadFor", "sourceChain", "FORMAT"],
};

let out = `// Generated by scripts/gen-abi.mjs from contracts/out — do not edit by hand.\n`;
out += `// Only the reads the interface actually makes; regenerate after a contract change.\n\n`;

for (const [name, fns] of Object.entries(WANT)) {
  const artifact = JSON.parse(readFileSync(`contracts/out/${name}.sol/${name}.json`, "utf8"));
  const picked = artifact.abi.filter((e) => e.type === "function" && fns.includes(e.name));
  const missing = fns.filter((f) => !picked.some((p) => p.name === f));
  if (missing.length) throw new Error(`${name}: artifact has no ${missing.join(", ")}`);
  const konst = name.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase() + "_ABI";
  out += `export const ${konst} = ${JSON.stringify(picked, null, 2)} as const;\n\n`;
}
writeFileSync("lib/registry-abi.ts", out);
console.log(`lib/registry-abi.ts — ${Object.keys(WANT).length} contracts, ${out.split("\n").length} lines`);

/**
 * Every function the deployed protocol has, by selector.
 *
 * Not the same list as lib/abi.ts, and that difference had a visible cost. The
 * app's ABI carries only the calls the interface makes, so anything resolving a
 * selector against it can name a call the interface makes and nothing else —
 * and the contract call log, which exists to show what has actually been done
 * to this contract, reported a third of its history as "unrecognised". They
 * were createTaskUntil, closeTask and submitTrajectoryFor: real functions of
 * the deployed contract that this frontend simply never calls.
 *
 * Generated from the compiler's own artifact, so it cannot name a function the
 * deployed contract does not have, and cannot miss one it does.
 */
const PROTOCOL = "AxonProtocolV2";
const artifact = JSON.parse(readFileSync(`contracts/out/${PROTOCOL}.sol/${PROTOCOL}.json`, "utf8"));
const ids = artifact.methodIdentifiers ?? JSON.parse(artifact.rawMetadata ?? "{}").output?.methodIdentifiers;
if (!ids || !Object.keys(ids).length) throw new Error(`${PROTOCOL}: artifact has no methodIdentifiers`);

const byName = {};
for (const [signature, selector] of Object.entries(ids)) {
  byName[`0x${selector}`] = signature.slice(0, signature.indexOf("("));
}

let methods = `// Generated by scripts/gen-abi.mjs from contracts/out/${PROTOCOL}.sol — do not edit by hand.\n`;
methods += `// Every function the deployed protocol has, by selector, so a call log can name\n`;
methods += `// one the interface never makes. Regenerate after a contract change.\n\n`;
methods += `export const PROTOCOL_METHODS: Record<string, string> = ${JSON.stringify(byName, null, 2)};\n`;
writeFileSync("lib/protocol-methods.ts", methods);
console.log(`lib/protocol-methods.ts — ${Object.keys(byName).length} selectors from ${PROTOCOL}`);
